query allProducts {
	Products {
		id
		name
		category
		description
		price
		imageUrl
	}
}

query singleProduct {
	Product(id: "ck8atgsrx0007kr7b3w3azya1") {
		id
		name
		category
		description
		price
		imageUrl
	}
}
