query allProducts {
	Products {
		id
		name
		category
		description
		price
		imageUrl
	}
}

query singleProduct {
	Product(id: "ck8atgsrx0007kr7b3w3azya1") {
		id
		name
		category
		description
		price
		imageUrl
	}
}

mutation addProduct {
	createProduct(
		name: "Hyperlite Riot Nova"
		category: "Wakeboards"
		description: "This is the Riot Nova, it's sick."
		price: "$799"
		imageUrl: "https://www.hyperlite.com/images/square.png"
	) {
		name
		category
		description
		price
		imageUrl
	}
}
