# Write your query or mutation here
query allProducts {
	Products {
		id
		name
		category
		description
		price
		imageUrl
	}
}

query singleProducts {
	Product(id: "ck8atgsrx0007kr7b3w3azya1") {
		id
		name
		category
		description
		price
		imageUrl
	}
}

query wakeboards {
	Wakeboards {
		id
		name
		category
		description
		price
		imageUrl
	}
}

query productCategory {
	Category(category: "Wakeboards") {
		id
		name
		category
		description
		price
		imageUrl
	}
}

mutation addProduct {
	createProduct(
		name: "Hyperlite Riot Nova"
		category: "Wakeboards"
		description: "This is the Riot Nova, it's sick."
		price: 799
		imageUrl: "https://www.hyperlite.com/images/square.png"
	) {
		id
		name
		category
		description
		price
		imageUrl
	}
}

mutation updateProduct {
	updateProduct(
		id: "ck8ckndoo0000kb7bi8gdw2li"
		description: "This is teh best wakeboard in existence. Ever. Don't even argue."
	) {
		id
		name
		category
		description
		price
		imageUrl
	}
}

mutation deleteProduct {
	deleteOneProduct(where: { id: "ck8gw1hpu0000lr7biier71xy" }) {
		id
		name
		category
	}
}
